server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/booking-service"
    username: root
    password: nhat
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  signerKey: "58242ea255084e90898781e7807ef38c133ae417acd124956609f828883401c9"

file:
  upload-dir: uploads/court-images

# Gemini API Configuration (Google AI Studio)
gemini:
  apiKey: "AIzaSyC0BsMg4CoFNCk3Z1fzrWZu1T6O17A5DNc"
  model: "gemini-2.5-flash"